import {motion} from 'motion/react'
import {ArrowRight,Landmark,Network,Store,Users,Warehouse} from 'lucide-react'
import {Link} from 'react-router-dom'
import SectionLabel from './SectionLabel'

const partners=[
 {icon:Users,title:'Farmers & growers',text:'The foundation of the supply chain and a vital source of regional agricultural produce.'},
 {icon:Store,title:'Traders & aggregators',text:'Trusted market relationships that extend sourcing reach and support year-round availability.'},
 {icon:Warehouse,title:'Processing units',text:'Rice mills and processors that turn agricultural output into market-ready produce.'},
 {icon:Landmark,title:'Institutional buyers',text:'Organisations that value transparent transactions, dependable volume and planned fulfilment.'},
]

export default function AboutContent(){return <>
 <section className="about-profile page-section"><div><SectionLabel number="03">Company profile</SectionLabel><h2>Organised trading with<br/><em>regional expertise.</em></h2></div><div className="about-profile-copy"><p>Based in Gondia, one of Maharashtra&apos;s important rice-producing regions, SHIVAM ENTERPRISES operates at the point where agricultural production meets commercial demand. The business procures and trades rice and paddy for established business buyers.</p><p>Our proprietorship structure enables direct decision-making and responsive coordination. Combined with local market knowledge, this allows the enterprise to act with speed while maintaining personal accountability in every relationship.</p><p>We are building a business known not only for the produce it supplies, but also for the clarity, consistency and professionalism with which every transaction is handled.</p></div></section>
 <section className="relationship-section page-section"><div className="relationship-head"><div><SectionLabel number="04" light>Our ecosystem</SectionLabel><h2>Strong relationships at<br/><em>every link.</em></h2></div><p>A resilient trading business depends on more than transactions. We invest in relationships across the agricultural value chain to create steady supply, informed decisions and shared growth.</p></div><div className="partner-grid">{partners.map(({icon:Icon,title,text},i)=><motion.article key={title} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}><Icon/><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></motion.article>)}</div></section>
 <section className="about-principles page-section"><div className="principles-statement"><Network/><span>The Shivam way</span><h2>Clear commitments.<br/>Consistent <em>action.</em></h2><p>Our working principles guide day-to-day decisions and the long-term direction of the enterprise.</p></div><div className="principles-list"><article><b>01</b><div><h3>Trade transparently</h3><p>Communicate quality, availability, pricing and delivery expectations clearly before commitments are made.</p></div></article><article><b>02</b><div><h3>Protect relationships</h3><p>Build repeat business through fairness, responsiveness and respect for every supply-chain partner.</p></div></article><article><b>03</b><div><h3>Improve continuously</h3><p>Strengthen storage, inventory practices and operational systems as market demand grows.</p></div></article><article><b>04</b><div><h3>Grow responsibly</h3><p>Create sustainable value for customers, suppliers, employees and the wider agricultural community.</p></div></article></div></section>
 <section className="about-impact page-section"><div><span>Long-term vision</span><h2>Growth that moves the<br/><em>whole chain forward.</em></h2></div><div><p>The next phase of SHIVAM ENTERPRISES will expand procurement capability, improve storage infrastructure and enhance inventory efficiency. These investments will help the business serve higher volumes and reach wider domestic and export-linked markets.</p><p>Beyond commercial growth, the project is intended to support agricultural trade in the region, create employment opportunities and build lasting value for stakeholders.</p><Link className="button button-gold" to="/infrastructure">See our expansion plan <ArrowRight size={18}/></Link></div></section>
 </>}
