import {useLocation} from 'react-router-dom'
import SectionLabel from './SectionLabel'
const content={
 '/':{label:'Our market approach',title:'Built for dependable, long-term trade.',items:[['Reliable sourcing','Our farmer, trader and processing-unit relationships help identify dependable supply across procurement cycles.'],['Buyer-focused fulfilment','We coordinate around each buyer’s required volume, timeline, destination and commercial expectations.'],['Responsible growth','Storage, inventory and procurement improvements will support greater scale without compromising discipline.']]},
 '/about':{label:'Our growth direction',title:'Growing with clarity and purpose.',items:[['Strengthen the foundation','We are investing in procurement reach, storage quality, inventory oversight and delivery coordination.'],['Reach wider markets','Our direction includes institutional buyers, government procurement programmes and export-linked demand.'],['Create shared value','Growth will create opportunity for suppliers, employees, service partners, customers and the local economy.']]},
 '/products':{label:'Procurement standards',title:'A disciplined approach to every requirement.',items:[['Requirement alignment','We establish commodity, quality, approximate volume, destination and delivery timing before confirmation.'],['Source coordination','Produce is matched through our network for availability, commercial value and intended use.'],['Dispatch planning','Documentation and logistics coordination support timely movement to the specified destination.']]},
 '/infrastructure':{label:'Expansion priorities',title:'Infrastructure for sustainable scale.',items:[['Procurement capacity','Stronger working capacity will help secure larger volumes during favourable market periods.'],['Storage improvement','Better facilities will support safe handling, segregation and protection of quality produce.'],['Inventory efficiency','Improved stock visibility will strengthen planning, order fulfilment and operating control.']]},
 '/contact':{label:'Before you enquire',title:'Helpful information for business buyers.',items:[['Who can enquire?','Rice millers, exporters, institutions, government procurement partners and established commodity traders.'],['What should you share?','Product, approximate quantity, quality parameters, destination and required delivery timeline.'],['Recurring requirements','Ongoing and volume-based supply can be discussed according to availability and specifications.']]},
}
export default function AdditionalContent(){const{pathname}=useLocation();const block=content[pathname]||content['/'];return <section className="additional-section page-section"><SectionLabel number="05">{block.label}</SectionLabel><div className="additional-heading"><h2>{block.title}</h2><p>SHIVAM ENTERPRISES combines local market knowledge with transparent processes to create consistent value across the agricultural supply chain.</p></div><div className="content-columns">{block.items.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>}
